version: 0.1
os: linux
files:
    - source: /
      destination: /home/ec2-user/vidly-app
hook:
    ApplicationStop:
        - location: scripts/applications_stop.sh
          timeout: 300
          runas: ec2-user
    BeforeInstall:
        - location: scripts/before_install.sh
          timeout: 300
          runas: ec2-user
    ApplicationStart:
        - location: scripts/application_start.sh
          timeout: 300
          runas: ec2-user
